/**
 * Пилотный учебный план ОП 6В01601 «Подготовка учителей истории»,
 * год набора 2026, 240 кредитов, 8 семестров.
 *
 * Источник — эталонный сид `seed_6b01601.sql` из комплекта ТЗ, полученный
 * из формы ЖН-31-22 ФР 01. Данные перенесены без изменений: валидатор ГОСО
 * должен подтверждать на них ровно нормативные объёмы (критерий приёмки № 1
 * раздела 8.1 ТЗ) — ООД 56 (51 ОК + 5 ВК), БД + ПД 176, ИА 8, итого 240
 * кредитов и 7200 часов.
 *
 * Файл сгенерирован, править вручную не нужно: при обновлении плана
 * заменяется целиком.
 */

export interface PilotSlotOption {
  code: string;
  abbrKk: string | null;
  abbrRu: string | null;
  abbrEn: string | null;
  nameKk: string;
  nameRu: string;
  nameEn: string | null;
  /** Привязка к обязательной дисциплине ГОСО (ГОСО, п. 6), если это она */
  gosoMandatorySlug: string | null;
  isPractice: boolean;
  isDefault: boolean;
  isMinorPlaceholder: boolean;
}

export interface PilotSlot {
  slotCode: string | null;
  /** Индекс в массиве modules */
  moduleIndex: number | null;
  cycle: 'OOD' | 'BD' | 'PD' | 'IA' | 'DVO';
  component: 'OK' | 'VK' | 'KV';
  credits: number;
  totalHours: number;
  hoursLecture: number;
  hoursLab: number;
  hoursPractice: number;
  hoursIndividual: number;
  hoursSrs: number;
  hoursSrsp: number;
  hoursPracticeField: number;
  hoursThesis: number;
  controlForm:
    | 'EXAM'
    | 'STATE_EXAM'
    | 'CREDIT_TEST'
    | 'COURSE_WORK'
    | 'PRACTICE_REPORT'
    | 'THESIS_DEFENSE'
    | 'COMPLEX_EXAM';
  hasCourseWork: boolean;
  terms: number[];
  creditsByTerm: Record<string, number>;
  controlTerm: number | null;
  teachingLang: string | null;
  chooseN: number;
  isMinorSlot: boolean;
  sortOrder: number;
  options: PilotSlotOption[];
}

export interface PilotCurriculum {
  program: {
    code: string;
    nameKk: string;
    nameRu: string;
    nameEn: string;
    eduAreaCode: string;
    eduAreaNameRu: string;
    trainingDirCode: string;
    trainingDirNameRu: string;
    degreeNameRu: string;
    isDualSubject: boolean;
    studyYears: number;
    gosoProfileCode: string;
    facultyCode: string;
    facultyNameKk: string;
    facultyNameRu: string;
    departmentCode: string;
    departmentNameKk: string;
    departmentNameRu: string;
  };
  curriculum: {
    admissionYear: number;
    version: number;
    studyForm: 'FULL_TIME' | 'PART_TIME' | 'DISTANCE' | 'EVENING';
    termsCount: number;
  };
  modules: { code: string | null; nameKk: string; nameRu: string; sortOrder: number }[];
  slots: PilotSlot[];
}

export const CURRICULUM_6B01601: PilotCurriculum = {
  program: {
    code: "6B01601",
    nameKk: "Тарих мұғалімдерін даярлау",
    nameRu: "Подготовка учителей истории",
    nameEn: "Training teachers of History",
    eduAreaCode: "6B01",
    eduAreaNameRu: "Педагогические науки",
    trainingDirCode: "6B016",
    trainingDirNameRu: "Образование по подготовке учителей гуманитарных дисциплин",
    degreeNameRu: "бакалавр образования",
    isDualSubject: false,
    studyYears: 4,
    gosoProfileCode: "BACHELOR_240",
    facultyCode: "ART_HUM",
    facultyNameKk: "Өнер және гуманитарлық білім беру факультеті",
    facultyNameRu: "Факультет искусства и гуманитарного образования",
    departmentCode: "HUM",
    departmentNameKk: "Гуманитарлық ғылымдар",
    departmentNameRu: "Гуманитарные науки",
  },
  curriculum: {
    admissionYear: 2026,
    version: 1,
    studyForm: "FULL_TIME",
    termsCount: 8,
  },
  modules: [
    { code: "KGM/ MON/ MSS", nameKk: "Қоғамдық ғылымдар модулі", nameRu: "Модуль общественных наук", sortOrder: 1 },
    { code: "ASBM/ MSPZ/ MSPK", nameKk: "Әлеуметтік-саяси білімдер модулі", nameRu: "Модуль социально-политических знаний", sortOrder: 2 },
    { code: "KUM/ MKM/ MCM", nameKk: "Коммуникативті ұтқырлық модул", nameRu: "Модуль коммуникативной мобильности", sortOrder: 3 },
    { code: "PPKD/ PPPP/ PPPT", nameKk: "Педагогикалық, психологиялық және кәсіби дайындық", nameRu: "Педагогическая, психологическая и профессиональная подготовка", sortOrder: 4 },
    { code: "KAEEOGT/ IKSMDS/ THKCWAMA", nameKk: "Қазақстанның және әлем елдерінің ежелгі және орта ғасырлар тарихы", nameRu: "История Казахстана и стран мира в древности и средневековье", sortOrder: 5 },
    { code: "TOKOOTA/ IGIAURK/ HGHASRK", nameKk: "Тарихи өлкетану және Қазақстанның Оңтүстік өңірінің тарихы мен археологиясы", nameRu: "Историческая география и история и археология Южного региона Казахстана", sortOrder: 6 },
    { code: "FATP/ FMID/ FMHD", nameKk: "Фундаментальды және әдістемелік тарихи пәндер", nameRu: "Фундаментальные и методические исторические дисциплины", sortOrder: 7 },
    { code: "MNTD/ OMTND/ FMTDS", nameKk: "Музейтану негіздері мен теориялық деректану", nameRu: "Основы музеологии и теоретической науки о данных", sortOrder: 8 },
    { code: "KHEAHETA/ EKNEIANM/ EKPEHAPW", nameKk: "Қазақ халқының этногенезі және әлем халықтарының этнологиясы мен тарихи антропологиясы", nameRu: "Этногенез казахского народа и этнология и историческая антропология народов мира", sortOrder: 9 },
    { code: "KADNADT/ AKORIRM/ AKFRSHRW", nameKk: "Қазақстан архивтері, дінтану негіздері және әлем діндерінің тарихы", nameRu: "Архивы Казахстана, основы религиоведения и история религий мира", sortOrder: 10 },
    { code: "TK/MВ/ KB/MP/ SC/MP/", nameKk: "Таңдау компоненті", nameRu: "Минор бағдарламасы Компонент по выбору", sortOrder: 11 },
    { code: "KAM/ MIA/ MFC", nameKk: "Қорытынды аттестация модулі", nameRu: "Модуль итоговой аттестации", sortOrder: 12 },
  ],
  slots: [
    {
      slotCode: "4101",
      moduleIndex: 0,
      cycle: "OOD",
      component: "OK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "STATE_EXAM",
      hasCourseWork: false,
      controlTerm: 7,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 1,
      terms: [7],
      creditsByTerm: { '7': 5 },
      options: [
        {
          code: "KT/ IK/ HK 4101",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақстан тарихы",
          nameRu: "История Казахстана",
          nameEn: "History of Kazakhstan",
          gosoMandatorySlug: "history_kz",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2102",
      moduleIndex: 0,
      cycle: "OOD",
      component: "OK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 2,
      terms: [4],
      creditsByTerm: { '4': 5 },
      options: [
        {
          code: "Fil/ Fil / Phil 2102",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Философия",
          nameRu: "Философия",
          nameEn: "Philosophy",
          gosoMandatorySlug: "philosophy",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1103",
      moduleIndex: 1,
      cycle: "OOD",
      component: "OK",
      credits: 4,
      totalHours: 120,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 60,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 3,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 3,
      terms: [3],
      creditsByTerm: { '3': 4 },
      options: [
        {
          code: "AS/ SP/ SPS 1103",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Әлеуметтану және саясаттану",
          nameRu: "Социология и политология",
          nameEn: "Social and Political Studies",
          gosoMandatorySlug: "sociopolit",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1104",
      moduleIndex: 1,
      cycle: "OOD",
      component: "OK",
      credits: 4,
      totalHours: 120,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 60,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 2,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 4,
      terms: [2],
      creditsByTerm: { '2': 4 },
      options: [
        {
          code: "MP/ KP/ CSP 1104",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Мәдениеттану және психология",
          nameRu: "Культурология и психология",
          nameEn: "Cultural Studies and Psychology",
          gosoMandatorySlug: "sociopolit",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2109",
      moduleIndex: 1,
      cycle: "OOD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 5,
      terms: [4],
      creditsByTerm: { '4': 5 },
      options: [
        {
          code: "KSNK/ OFGP/ FFLE 2109",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қаржылық сауаттылық негіздері және кәсіпкерлік",
          nameRu: "Основы финансовой грамотности и предпринимательства",
          nameEn: "Fundamentals of Financial Literacy and Entrepreneurship",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "ETKN/ OEBJ/ FELS 2109",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Экология және тіршілік қауіпсіздікі негіздері",
          nameRu: "Основы экологии и безопасности жизнедеятельности",
          nameEn: "Fundamentals of ecology and life safety",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
        {
          code: "EKN/ OEP/ BEL 2109",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Экономика және құқық негіздері",
          nameRu: "Основы экономики и права",
          nameEn: "Basics of Economics and Law",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
        {
          code: "SZhKKMN/ OAK/ FACC 2109",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Сыбайлас жемқорлыққа қарсы күрес мәдениеті негіздері",
          nameRu: "Основы антикоррупционной культуры",
          nameEn: "Fundamentals of Anti-Corruption Culture",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
        {
          code: "GZA/ MNI/ MSR 2109",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Ғылыми зерттеу әдістері",
          nameRu: "Методы научного исследования",
          nameEn: "Methods of Scientific Research",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1105",
      moduleIndex: 2,
      cycle: "OOD",
      component: "OK",
      credits: 10,
      totalHours: 300,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 120,
      hoursIndividual: 0,
      hoursSrs: 150,
      hoursSrsp: 30,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 2,
      teachingLang: "II",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 6,
      terms: [1, 2],
      creditsByTerm: { '1': 5, '2': 5 },
      options: [
        {
          code: "K(O)T/ K(R)Ya/ K(R)L 1105",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақ (Орыс) тілі",
          nameRu: "Казахский (Русский) язык",
          nameEn: "Kazakh (Russian) Language",
          gosoMandatorySlug: "state_lang",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1106",
      moduleIndex: 2,
      cycle: "OOD",
      component: "OK",
      credits: 10,
      totalHours: 300,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 120,
      hoursIndividual: 0,
      hoursSrs: 150,
      hoursSrsp: 30,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 2,
      teachingLang: "III",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 7,
      terms: [1, 2],
      creditsByTerm: { '1': 5, '2': 5 },
      options: [
        {
          code: "Sht/ IYa/ FL 1106",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Шетел тілі",
          nameRu: "Иностранный язык",
          nameEn: "Foreign Language",
          gosoMandatorySlug: "foreign_lang",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1(2)107",
      moduleIndex: 2,
      cycle: "OOD",
      component: "OK",
      credits: 8,
      totalHours: 240,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 240,
      hoursIndividual: 0,
      hoursSrs: 0,
      hoursSrsp: 0,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "CREDIT_TEST",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: "І",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 8,
      terms: [1, 2, 3, 4],
      creditsByTerm: { '1': 2, '2': 2, '3': 2, '4': 2 },
      options: [
        {
          code: "DSh / FK/ PT 1(2)107",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Дене шынықтыру",
          nameRu: "Физическая культура",
          nameEn: "Physical Training",
          gosoMandatorySlug: "phys_culture",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3201",
      moduleIndex: 2,
      cycle: "BD",
      component: "VK",
      credits: 3,
      totalHours: 90,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 45,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "CREDIT_TEST",
      hasCourseWork: false,
      controlTerm: 5,
      teachingLang: "II",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 9,
      terms: [5],
      creditsByTerm: { '5': 3 },
      options: [
        {
          code: "KK(O)T/ PK(R)Ya/ PK(R)L 3201",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Кәсіби қазақ (орыс ) тілі",
          nameRu: "Профессиональный казахский (руский) язык",
          nameEn: "Professional Kazakh (Russian) Language",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2202",
      moduleIndex: 2,
      cycle: "BD",
      component: "VK",
      credits: 3,
      totalHours: 90,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 45,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: "III",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 10,
      terms: [4],
      creditsByTerm: { '4': 3 },
      options: [
        {
          code: "KBShT/ POIYa/ POFL 2202",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Кәсіби-бағытталған шетел тілі",
          nameRu: "Профессионально- ориентированный иностранный язык",
          nameEn: "Professionally Oriented Foreign Language",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2203",
      moduleIndex: 2,
      cycle: "BD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 11,
      terms: [4],
      creditsByTerm: { '4': 5 },
      options: [
        {
          code: "ZhIN/ OII/ FAI 2203",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Жасанды интеллект негіздері",
          nameRu: "Основы искусственного интеллекта",
          nameEn: "Fundamentals of artificial intelligence",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2108",
      moduleIndex: 2,
      cycle: "OOD",
      component: "OK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 30,
      hoursPractice: 0,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 3,
      teachingLang: "І",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 12,
      terms: [3],
      creditsByTerm: { '3': 5 },
      options: [
        {
          code: "AKT/ IKT/ ICT 2108",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Ақпараттық-коммуникациялық технологиялар",
          nameRu: "Информационно-коммуникационные технологии",
          nameEn: "Information and Communication Technologies",
          gosoMandatorySlug: "ict",
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3204",
      moduleIndex: 3,
      cycle: "BD",
      component: "VK",
      credits: 3,
      totalHours: 90,
      hoursLecture: 15,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 45,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 13,
      terms: [6],
      creditsByTerm: { '6': 3 },
      options: [
        {
          code: "OFPD/ FPRU/ PPDS 3204",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Оқушылардың физиологиялық және психологиялық дамуы",
          nameRu: "Физиологическое и психологическое развитие учащихся",
          nameEn: "Physiological and Psychological Development of Students",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3205",
      moduleIndex: 3,
      cycle: "BD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 5,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 14,
      terms: [5],
      creditsByTerm: { '5': 5 },
      options: [
        {
          code: "PTZhA/ PMVR/ PMEW 3205",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Педагогика және тәрбие жұмысының әдістемесі",
          nameRu: "Педагогика и методика воспитательной работы",
          nameEn: "Pedagogy and Methods of Educational Work",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1206",
      moduleIndex: 3,
      cycle: "BD",
      component: "VK",
      credits: 3,
      totalHours: 90,
      hoursLecture: 15,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 45,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 2,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 15,
      terms: [2],
      creditsByTerm: { '2': 3 },
      options: [
        {
          code: "IBB/ IO/ IE 1206",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Инклюзивті білім беру",
          nameRu: "Инклюзивное образование",
          nameEn: "Inclusive Education",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2207",
      moduleIndex: 3,
      cycle: "BD",
      component: "VK",
      credits: 2,
      totalHours: 60,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 0,
      hoursIndividual: 0,
      hoursSrs: 0,
      hoursSrsp: 0,
      hoursPracticeField: 60,
      hoursThesis: 0,
      controlForm: "PRACTICE_REPORT",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: null,
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 16,
      terms: [4],
      creditsByTerm: { '4': 2 },
      options: [
        {
          code: "KP/ KP/ PP 2207",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Кәсіби практика (Психологиялық -педагогикалық практика)",
          nameRu: "Профессиональная практика( Психолого-педагогическая практика)",
          nameEn: "Professional Practice (The psycho-pedagogical practice)",
          gosoMandatorySlug: null,
          isPractice: true,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2208",
      moduleIndex: 2,
      cycle: "BD",
      component: "VK",
      credits: 3,
      totalHours: 90,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 45,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 3,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 17,
      terms: [3],
      creditsByTerm: { '3': 3 },
      options: [
        {
          code: "АХ АП AW 2208",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Академиялық хат",
          nameRu: "Академическое письмо",
          nameEn: "Academic Writing",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1216",
      moduleIndex: 0,
      cycle: "BD",
      component: "KV",
      credits: 3,
      totalHours: 90,
      hoursLecture: 15,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 45,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 1,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 18,
      terms: [1],
      creditsByTerm: { '1': 3 },
      options: [
        {
          code: "TТ/ TV/ TS 1216",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Тәшеневтану",
          nameRu: "Ташеневоведение",
          nameEn: "Tashenev Studies",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "АТ АV AV 1216",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Абайтану",
          nameRu: "Абаяведение",
          nameEn: "Abay Studies",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1209",
      moduleIndex: 4,
      cycle: "BD",
      component: "VK",
      credits: 4,
      totalHours: 120,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 60,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 1,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 19,
      terms: [1],
      creditsByTerm: { '1': 4 },
      options: [
        {
          code: "КET/ DIK/ AHK 1209",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақстанның ежелгі тарихы",
          nameRu: "Древняя история Казахстана",
          nameEn: "Ancient History of Kazakhstan",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1210",
      moduleIndex: 4,
      cycle: "BD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 1,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 20,
      terms: [1],
      creditsByTerm: { '1': 5 },
      options: [
        {
          code: "EDT/ IDM/ AH 1210",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Ежелгі дүние жүзі тарихы",
          nameRu: "История древнего мира",
          nameEn: "Ancient History",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2211",
      moduleIndex: 4,
      cycle: "BD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 3,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 21,
      terms: [3],
      creditsByTerm: { '3': 5 },
      options: [
        {
          code: "OGKT/ ISK/ HMK 2211",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Орта ғасырдағы Қазақстан тарихы",
          nameRu: "История средневекового Казахстана",
          nameEn: "History of Medieval Kazakhstan",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2212",
      moduleIndex: 4,
      cycle: "BD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 3,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 22,
      terms: [3],
      creditsByTerm: { '3': 5 },
      options: [
        {
          code: "OGT/ ISV/ HMA 2212",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Орта ғасырлар тарихы (Батыс)",
          nameRu: "История Средних веков (Западный)",
          nameEn: "History of the Middle Ages (Western)",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "2213",
      moduleIndex: 4,
      cycle: "BD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 3,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 23,
      terms: [3],
      creditsByTerm: { '3': 5 },
      options: [
        {
          code: "OGShET/ ISVS/ HECMA 2213",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Орта ғасырдағы шығыс елдерінің тарихы",
          nameRu: "История стран Востока в средневековье",
          nameEn: "History of the Eastern Countries in the Middle Ages",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1214",
      moduleIndex: 4,
      cycle: "BD",
      component: "VK",
      credits: 2,
      totalHours: 60,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 0,
      hoursIndividual: 0,
      hoursSrs: 0,
      hoursSrsp: 0,
      hoursPracticeField: 60,
      hoursThesis: 0,
      controlForm: "PRACTICE_REPORT",
      hasCourseWork: false,
      controlTerm: 2,
      teachingLang: null,
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 24,
      terms: [2],
      creditsByTerm: { '2': 2 },
      options: [
        {
          code: "KP/ PP/ PP) 1214",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Кәсіби практика (оқу танысу)",
          nameRu: "Профессиональная практика (учебно-ознакомительная)",
          nameEn: "Professional Practice (educational and familiarization)",
          gosoMandatorySlug: null,
          isPractice: true,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1217",
      moduleIndex: 5,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 1,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 25,
      terms: [1],
      creditsByTerm: { '1': 5 },
      options: [
        {
          code: "Arh/ Arh/ Arch 1217",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Археология",
          nameRu: "Археология",
          nameEn: "Archaeology",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "KA/ AK/ AK 1217",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақстан археологиясы",
          nameRu: "Археология Казахстана",
          nameEn: "Archaeology Of Kazakhstan",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1218",
      moduleIndex: 5,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 2,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 26,
      terms: [2],
      creditsByTerm: { '2': 5 },
      options: [
        {
          code: "TON/ OIK/ BHLH 1218",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Тарихи өлкетану негіздері",
          nameRu: "Основы исторического краеведения",
          nameEn: "Bases of Historical Local History",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "MOTME/ IKPMR/ HCMMR 1218",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Мырзашөл өңіріндегі тарихи-мәдени ескерткіштер",
          nameRu: "Историко-культурные памятники Мырзашольского региона",
          nameEn: "Historical and Сultural Monuments of the Myrzashol Region",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "4306",
      moduleIndex: 5,
      cycle: "PD",
      component: "KV",
      credits: 6,
      totalHours: 180,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 45,
      hoursIndividual: 0,
      hoursSrs: 90,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 7,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 27,
      terms: [7],
      creditsByTerm: { '7': 6 },
      options: [
        {
          code: "KZKB/ ZSE/ WME 4306",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазіргі заман кезеңіндегі Батыс",
          nameRu: "Запад в современную эпоху",
          nameEn: "The West in the modern era",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "GT/ IG/ HG 4306",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Германия тарихы",
          nameRu: "История Германии",
          nameEn: "History of the Germany",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "4307",
      moduleIndex: 5,
      cycle: "PD",
      component: "KV",
      credits: 6,
      totalHours: 180,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 45,
      hoursIndividual: 0,
      hoursSrs: 90,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 7,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 28,
      terms: [7],
      creditsByTerm: { '7': 6 },
      options: [
        {
          code: "KZKSh/ VSE/ EME 4307",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазіргі заман кезеңіндегі Шығыс Восток в современную эпоху",
          nameRu: "The East in the modern era",
          nameEn: "The East in the modern era",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "KSROMTMDET/ ISSRISSNG/ HUSSRCISC 4307",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "КСРО мен ТМД елдерінің тарихы",
          nameRu: "История СССР и стран СНГ",
          nameEn: "History of the USSR and CIS countries",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3219",
      moduleIndex: 5,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 29,
      terms: [6],
      creditsByTerm: { '6': 5 },
      options: [
        {
          code: "KZhZT/ NIK/ NHK 3219",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақстанның жаңа заман тарихы",
          nameRu: "Новая история Казахстана",
          nameEn: "New History of Kazakhstan",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "AKT/ IDA/ HAM 3219",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Алаш қозғалысының тарихы",
          nameRu: "История движения Алашa",
          nameEn: "History of Alash Movement",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3220",
      moduleIndex: 5,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 30,
      terms: [6],
      creditsByTerm: { '6': 5 },
      options: [
        {
          code: "HKJBSchET/ IMOSZW/ HIRBCWE 3220",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Халықаралық қатынастар жүйесіндегі Батыс және Шығыс елдерінің тарихы",
          nameRu: "История международных отношений стран Запада и Востока",
          nameEn: "The history of international relations between the countries of the West and the East",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "KZKhKT/ IMONV/ HIRMT 3220",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазіргі замандағы халықаралық қатынастардың тарихы",
          nameRu: "История международных отношений в наше время",
          nameEn: "History of International Relations in Modern Times",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3301",
      moduleIndex: 6,
      cycle: "PD",
      component: "VK",
      credits: 6,
      totalHours: 180,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 45,
      hoursIndividual: 0,
      hoursSrs: 90,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 5,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 31,
      terms: [5],
      creditsByTerm: { '5': 6 },
      options: [
        {
          code: "MOBIAT/ IMOOSh/ IMTESh 3301",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Мектепте оқыту мен бағалаудың инновациялық әдіс тәсілдері",
          nameRu: "Инновационные методы к обучению и оценке в школе",
          nameEn: "Innovative Methods for Teaching and Evaluation at School",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3302",
      moduleIndex: 6,
      cycle: "PD",
      component: "VK",
      credits: 6,
      totalHours: 180,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 45,
      hoursIndividual: 0,
      hoursSrs: 90,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 32,
      terms: [5],
      creditsByTerm: { '5': 6 },
      options: [
        {
          code: "TOA/ MPI/ HTM 3302",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Тарихты оқыту әдістемесі",
          nameRu: "Методика преподавания истории",
          nameEn: "History Teaching Methodology",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "4303",
      moduleIndex: 6,
      cycle: "PD",
      component: "VK",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 7,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 33,
      terms: [7],
      creditsByTerm: { '7': 5 },
      options: [
        {
          code: "Tar/ Ist/ His 4303",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Тарихнама",
          nameRu: "Историография",
          nameEn: "Historiography",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3221",
      moduleIndex: 6,
      cycle: "BD",
      component: "KV",
      credits: 4,
      totalHours: 120,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 60,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 34,
      terms: [6],
      creditsByTerm: { '6': 4 },
      options: [
        {
          code: "KDT/ IKD/ HKD 3221",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақ диаспорасының тарихы",
          nameRu: "История казахской диаспоры",
          nameEn: "History of the Kazakh Diasporatan",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "TD/ ID/ HD 3221",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Тарихи демография",
          nameRu: "Историческая демография",
          nameEn: "Historical demographics",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3215",
      moduleIndex: 6,
      cycle: "BD",
      component: "VK",
      credits: 4,
      totalHours: 120,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 0,
      hoursIndividual: 0,
      hoursSrs: 0,
      hoursSrsp: 0,
      hoursPracticeField: 120,
      hoursThesis: 0,
      controlForm: "PRACTICE_REPORT",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: null,
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 35,
      terms: [6],
      creditsByTerm: { '6': 4 },
      options: [
        {
          code: "KP/ PP/ PP 3215",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Кәсіби практика (Педагогикалық практика)",
          nameRu: "Профессиональная практика (Педагогическая практика)",
          nameEn: "Professional Practice (Pedagogical practice)",
          gosoMandatorySlug: null,
          isPractice: true,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "4304",
      moduleIndex: 6,
      cycle: "PD",
      component: "VK",
      credits: 8,
      totalHours: 240,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 0,
      hoursIndividual: 0,
      hoursSrs: 0,
      hoursSrsp: 0,
      hoursPracticeField: 240,
      hoursThesis: 0,
      controlForm: "PRACTICE_REPORT",
      hasCourseWork: false,
      controlTerm: 7,
      teachingLang: null,
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 36,
      terms: [7],
      creditsByTerm: { '7': 8 },
      options: [
        {
          code: "KP/ KP/ PP 4304",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Кәсіби практика (Өндірістік педагогикалық практика)",
          nameRu: "Профессиональная практика( Производственная педагогическая практика)",
          nameEn: "Professional Practice (Productive рedagogical practice)",
          gosoMandatorySlug: null,
          isPractice: true,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3226",
      moduleIndex: 7,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 37,
      terms: [6],
      creditsByTerm: { '6': 5 },
      options: [
        {
          code: "TD/ TI/ TSS 3226",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Теориялық деректану",
          nameRu: "Теоретическое источниковедение",
          nameEn: "Theoretical Source Studies",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "ShTT/ IZI/ HFH 3226",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Шетел тарихының тарихнамасы",
          nameRu: "Историография зарубежной истории",
          nameEn: "Historiography of Foreign History",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3222",
      moduleIndex: 7,
      cycle: "BD",
      component: "KV",
      credits: 4,
      totalHours: 120,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 60,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 38,
      terms: [4],
      creditsByTerm: { '4': 4 },
      options: [
        {
          code: "MN/ OM/ FMS 3222",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Музейтану негіздері",
          nameRu: "Основы музееведения",
          nameEn: "Fundamentals of Museum Studies",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "AMT/ IMM/ HWM 3222",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Әлем музейлерінің тарихы",
          nameRu: "История музеев мира",
          nameEn: "History of World Museums",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3223",
      moduleIndex: 8,
      cycle: "BD",
      component: "KV",
      credits: 4,
      totalHours: 120,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 15,
      hoursIndividual: 0,
      hoursSrs: 60,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 6,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 39,
      terms: [6],
      creditsByTerm: { '6': 4 },
      options: [
        {
          code: "AHE/ ENM/ EPW 3223",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Әлем халықтарының этнологиясы",
          nameRu: "Этнология народов мира",
          nameEn: "Ethnology of the Peoples of the World",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "KHEET/ EEIKN/ EEHKP 3223",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақ халқының этногенезі мен этникалық тарихы",
          nameRu: "Этногенез и этническая история казахского народа",
          nameEn: "Ethnogenesis and Ethnic History of the Kazakh People",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "1308",
      moduleIndex: 8,
      cycle: "PD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 2,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 40,
      terms: [2],
      creditsByTerm: { '2': 5 },
      options: [
        {
          code: "KTP/ BID/ AHD 1308",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қосалқы тарихи пәндер",
          nameRu: "Вспомогательные исторические дисциплины",
          nameEn: "Auxiliary Historical Disciplines",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "TA/ IA/ HA 1308",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Тарихи антропология",
          nameRu: "Историческая антропология",
          nameEn: "Historical Anthropology",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "4309",
      moduleIndex: 9,
      cycle: "PD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 7,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 41,
      terms: [7],
      creditsByTerm: { '7': 5 },
      options: [
        {
          code: "ADT/ IMR/ HWR 4309",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Әлем діндерінің тарихы",
          nameRu: "История мировых религий",
          nameEn: "History of World Religions",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "IT/ II/ HI 4309",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Ислам тарихы",
          nameRu: "История ислама",
          nameEn: "History of Islam",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "4310",
      moduleIndex: 9,
      cycle: "PD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 7,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 42,
      terms: [7],
      creditsByTerm: { '7': 5 },
      options: [
        {
          code: "AN/ OA/ BAS 4310",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Архивтану негіздері",
          nameRu: "Основы архивоведения",
          nameEn: "Basics of Archival Science",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "KA/ AK/ AK 4310",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақстан архивтері",
          nameRu: "Архивы Казахстана",
          nameEn: "Archives Of Kazakhstan",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "3224",
      moduleIndex: 10,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 5,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: true,
      sortOrder: 43,
      terms: [5],
      creditsByTerm: { '5': 5 },
      options: [
        {
          code: "JZB/ ZNV/ WMT 3224",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Жаңа замандағы Батыс",
          nameRu: "Запад в Новое время",
          nameEn: "The West in Modern Times",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "PRKOSZ/ PKPZRK/ CTRCPK 3224",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Патшалық Ресейдің Қазақстандағы отарлау саясатының зардаптары",
          nameRu: "Последствия колониальной политики царской России в Казахстане",
          nameEn: "The consequences of Tsarist Russia's colonial policy in Kazakhstan",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
        {
          code: "MBP1/ MPD1/ MPD1 3224",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "МИНОР БАҒДАРЛАМАСЫ - пән 1",
          nameRu: "МИНОР ПРОГРАММА-дисциплина 1",
          nameEn: "MINOR PROGRAM – discipline 1",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: true,
        },
      ],
    },
    {
      slotCode: "3225",
      moduleIndex: 10,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 5,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: true,
      sortOrder: 44,
      terms: [5],
      creditsByTerm: { '5': 5 },
      options: [
        {
          code: "JZSh/ VNV/ EMT 3225",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Жаңа замандағы Шығыс",
          nameRu: "Восток в Новое время",
          nameEn: "The East in Modern Times",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "OT/ IS/ HC 3225",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Өркениеттер тарихы",
          nameRu: "История цивилизации",
          nameEn: "History of Сivilization",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
        {
          code: "MBP2/ MPD2/ MPD2 3225",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "МИНОР БАҒДАРЛАМАСЫ-пән 2",
          nameRu: "МИНОР ПРОГРАММА-дисциплина 2",
          nameEn: "MINOR PROGRAM – discipline 2",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: true,
        },
      ],
    },
    {
      slotCode: "2226",
      moduleIndex: 10,
      cycle: "BD",
      component: "KV",
      credits: 5,
      totalHours: 150,
      hoursLecture: 30,
      hoursLab: 0,
      hoursPractice: 30,
      hoursIndividual: 0,
      hoursSrs: 75,
      hoursSrsp: 15,
      hoursPracticeField: 0,
      hoursThesis: 0,
      controlForm: "EXAM",
      hasCourseWork: false,
      controlTerm: 4,
      teachingLang: "I",
      chooseN: 1,
      isMinorSlot: true,
      sortOrder: 45,
      terms: [4],
      creditsByTerm: { '4': 5 },
      options: [
        {
          code: "THT/ ITN/ HTP 2226",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Түркі халықтарының тарихы",
          nameRu: "История тюркских народов",
          nameEn: "History of the Turkic Peoples",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
        {
          code: "KTET/ EIKT/ EHKT 2226",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Қазақ түркілерінің этникалық тарихы",
          nameRu: "Этническая история казахских тюрков",
          nameEn: "Ethnic History of the Kazakh Turks",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: false,
        },
        {
          code: "MBP3/ MPD3/ MPD3 2226",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "МИНОР БАҒДАРЛАМАСЫ-пән 3",
          nameRu: "МИНОР ПРОГРАММА-дисциплина 3",
          nameEn: "MINOR PROGRAM – discipline 3",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: false,
          isMinorPlaceholder: true,
        },
      ],
    },
    {
      slotCode: "4305",
      moduleIndex: 11,
      cycle: "PD",
      component: "VK",
      credits: 12,
      totalHours: 360,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 0,
      hoursIndividual: 0,
      hoursSrs: 0,
      hoursSrsp: 0,
      hoursPracticeField: 360,
      hoursThesis: 0,
      controlForm: "THESIS_DEFENSE",
      hasCourseWork: false,
      controlTerm: 8,
      teachingLang: null,
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 46,
      terms: [8],
      creditsByTerm: { '8': 12 },
      options: [
        {
          code: "DAOP/ PPP/ PIP 4305",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Диплом алды және өндірістік практика",
          nameRu: "Преддипломная и производственная практика",
          nameEn: "Pre-graduate and Industrial Practice",
          gosoMandatorySlug: null,
          isPractice: true,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
    {
      slotCode: "4305",
      moduleIndex: 11,
      cycle: "IA",
      component: "VK",
      credits: 8,
      totalHours: 240,
      hoursLecture: 0,
      hoursLab: 0,
      hoursPractice: 0,
      hoursIndividual: 0,
      hoursSrs: 0,
      hoursSrsp: 0,
      hoursPracticeField: 0,
      hoursThesis: 240,
      controlForm: "THESIS_DEFENSE",
      hasCourseWork: false,
      controlTerm: 8,
      teachingLang: null,
      chooseN: 1,
      isMinorSlot: false,
      sortOrder: 47,
      terms: [8],
      creditsByTerm: { '8': 8 },
      options: [
        {
          code: "IA 4305",
          abbrKk: null,
          abbrRu: null,
          abbrEn: null,
          nameKk: "Дипломдық жұмысты (жобаны) жазу және қорғау немесе кешенді емтихан тапсыру",
          nameRu: "Написание и защита дипломной работы (проекта) или сдача комплексного экзамена",
          nameEn: "Writing and Defence of Degree Work (project) or Passing a Graded Exam",
          gosoMandatorySlug: null,
          isPractice: false,
          isDefault: true,
          isMinorPlaceholder: false,
        },
      ],
    },
  ],
};
