/**
 * Демонстрационные данные — исходные значения.
 *
 * ВНИМАНИЕ. Все персональные данные вымышлены. ИИН сгенерированы алгоритмически
 * и корректны по контрольному разряду, но не принадлежат реальным лицам.
 * Демо-набор предназначен для пилотной эксплуатации на обезличенных данных
 * (раздел 2.2 ТЗ) и не должен использоваться в промышленной среде.
 */

export const FACULTY = {
  code: 'ITF',
  nameKk: 'Ақпараттық технологиялар факультеті',
  nameRu: 'Факультет информационных технологий',
  nameEn: 'Faculty of Information Technology',
};

export const DEPARTMENTS = [
  {
    code: 'CS',
    nameKk: 'Информатика және есептеу техникасы кафедрасы',
    nameRu: 'Кафедра информатики и вычислительной техники',
    nameEn: 'Department of Computer Science',
  },
  {
    code: 'MATH',
    nameKk: 'Жоғары математика кафедрасы',
    nameRu: 'Кафедра высшей математики',
    nameEn: 'Department of Mathematics',
  },
];

export const PROGRAMS = [
  {
    code: '6B06103',
    departmentCode: 'CS',
    nameKk: 'Ақпараттық жүйелер',
    nameRu: 'Информационные системы',
    nameEn: 'Information Systems',
    level: 'BACHELOR' as const,
    language: 'RU' as const,
    durationYears: 4,
    totalCredits: 240,
  },
  {
    code: '6B06102',
    departmentCode: 'CS',
    nameKk: 'Бағдарламалық инженерия',
    nameRu: 'Программная инженерия',
    nameEn: 'Software Engineering',
    level: 'BACHELOR' as const,
    language: 'KK' as const,
    durationYears: 4,
    totalCredits: 240,
  },
];

export const DISCIPLINES = [
  {
    code: 'INF1201',
    departmentCode: 'CS',
    programCode: '6B06103',
    nameKk: 'Ақпараттық жүйелерге кіріспе',
    nameRu: 'Введение в информационные системы',
    nameEn: 'Introduction to Information Systems',
    credits: 3,
    cycle: 'BD' as const,
    component: 'OK' as const,
    language: 'RU' as const,
    gradingProfile: 'STANDARD' as const,
    learningOutcomesRu: [
      'объяснять назначение и состав информационной системы предприятия;',
      'классифицировать информационные системы по назначению и архитектуре;',
      'описывать жизненный цикл информационной системы;',
      'формулировать требования к информационной системе;',
      'оценивать качество информационной системы по установленным критериям.',
    ].join('\n'),
    learningOutcomesKk: [
      'кәсіпорынның ақпараттық жүйесінің мақсаты мен құрамын түсіндіру;',
      'ақпараттық жүйелерді мақсаты мен архитектурасы бойынша жіктеу;',
      'ақпараттық жүйенің өмірлік циклін сипаттау;',
      'ақпараттық жүйеге қойылатын талаптарды тұжырымдау;',
      'ақпараттық жүйенің сапасын белгіленген критерийлер бойынша бағалау.',
    ].join('\n'),
  },
  {
    code: 'INF2105',
    departmentCode: 'CS',
    programCode: '6B06103',
    nameKk: 'Деректер қорын жобалау',
    nameRu: 'Проектирование баз данных',
    nameEn: 'Database Design',
    credits: 5,
    cycle: 'PD' as const,
    component: 'VK' as const,
    language: 'RU' as const,
    gradingProfile: 'STANDARD' as const,
    learningOutcomesRu: [
      'строить концептуальную модель предметной области;',
      'выполнять нормализацию отношений до третьей нормальной формы;',
      'проектировать физическую структуру базы данных;',
      'составлять запросы на языке SQL, включая соединения и оконные функции;',
      'обосновывать выбор индексов и оценивать план выполнения запроса.',
    ].join('\n'),
  },
  {
    code: 'INF2210',
    departmentCode: 'CS',
    programCode: '6B06102',
    nameKk: 'Веб-қосымшаларды әзірлеу',
    nameRu: 'Разработка веб-приложений',
    nameEn: 'Web Application Development',
    credits: 5,
    cycle: 'PD' as const,
    component: 'KV' as const,
    language: 'KK' as const,
    gradingProfile: 'STANDARD' as const,
  },
  {
    code: 'MAT1101',
    departmentCode: 'MATH',
    programCode: '6B06103',
    nameKk: 'Математикалық талдау',
    nameRu: 'Математический анализ',
    nameEn: 'Mathematical Analysis',
    credits: 5,
    cycle: 'BD' as const,
    component: 'OK' as const,
    language: 'RU' as const,
    gradingProfile: 'STANDARD' as const,
  },
  {
    code: 'MAT1203',
    departmentCode: 'MATH',
    programCode: '6B06103',
    nameKk: 'Дискретті математика',
    nameRu: 'Дискретная математика',
    nameEn: 'Discrete Mathematics',
    credits: 4,
    cycle: 'BD' as const,
    component: 'OK' as const,
    language: 'RU' as const,
    gradingProfile: 'STANDARD' as const,
  },
  {
    code: 'LAN1102',
    departmentCode: 'CS',
    programCode: '6B06103',
    nameKk: 'Кәсіби бағытталған шет тілі',
    nameRu: 'Профессионально ориентированный иностранный язык',
    nameEn: 'Professional Foreign Language',
    credits: 3,
    cycle: 'OOD' as const,
    component: 'OK' as const,
    language: 'EN' as const,
    // Профиль Приложения 2 с привязкой к уровням ОЕК (вопрос 14.2.6 ТЗ)
    gradingProfile: 'LANGUAGE' as const,
  },
  {
    code: 'INF3301',
    departmentCode: 'CS',
    programCode: '6B06102',
    nameKk: 'Бағдарламалық қамтамасыз етуді тестілеу',
    nameRu: 'Тестирование программного обеспечения',
    nameEn: 'Software Testing',
    credits: 4,
    cycle: 'PD' as const,
    component: 'KV' as const,
    language: 'RU' as const,
    gradingProfile: 'STANDARD' as const,
  },
  {
    code: 'INF3405',
    departmentCode: 'CS',
    programCode: '6B06103',
    nameKk: 'Ақпараттық қауіпсіздік',
    nameRu: 'Информационная безопасность',
    nameEn: 'Information Security',
    credits: 4,
    cycle: 'PD' as const,
    component: 'VK' as const,
    language: 'RU' as const,
    gradingProfile: 'STANDARD' as const,
  },
];

export const TEACHERS = [
  {
    email: 'a.nurgaliev@demo.example.kz',
    lastNameKk: 'Нұрғалиев', firstNameKk: 'Асхат', middleNameKk: 'Маратұлы',
    lastNameRu: 'Нургалиев', firstNameRu: 'Асхат', middleNameRu: 'Маратович',
    lastNameEn: 'Nurgaliyev', firstNameEn: 'Askhat',
    departmentCode: 'CS',
    position: 'доцент',
    academicDegree: 'кандидат технических наук',
    roles: ['TEACHER'] as const,
  },
  {
    email: 'g.tulegenova@demo.example.kz',
    lastNameKk: 'Төлегенова', firstNameKk: 'Гүлнар', middleNameKk: 'Serikқызы',
    lastNameRu: 'Тулегенова', firstNameRu: 'Гульнар', middleNameRu: 'Сериковна',
    lastNameEn: 'Tulegenova', firstNameEn: 'Gulnar',
    departmentCode: 'CS',
    position: 'старший преподаватель',
    academicDegree: 'магистр информационных систем',
    roles: ['TEACHER', 'ADVISOR'] as const,
  },
  {
    email: 'd.karimov@demo.example.kz',
    lastNameKk: 'Кәрімов', firstNameKk: 'Данияр', middleNameKk: 'Болатұлы',
    lastNameRu: 'Каримов', firstNameRu: 'Данияр', middleNameRu: 'Болатович',
    lastNameEn: 'Karimov', firstNameEn: 'Daniyar',
    departmentCode: 'MATH',
    position: 'профессор',
    academicDegree: 'доктор физико-математических наук',
    roles: ['TEACHER'] as const,
  },
];

export const STAFF = [
  {
    email: 'admin@demo.example.kz',
    lastNameKk: 'Әбілқасым', firstNameKk: 'Ержан',
    lastNameRu: 'Абилькасым', firstNameRu: 'Ержан',
    lastNameEn: 'Abilkassym', firstNameEn: 'Yerzhan',
    roles: ['ADMIN'] as const,
  },
  {
    email: 'registrar@demo.example.kz',
    lastNameKk: 'Сағындықова', firstNameKk: 'Айнұр',
    lastNameRu: 'Сагындыкова', firstNameRu: 'Айнур',
    lastNameEn: 'Sagyndykova', firstNameEn: 'Ainur',
    roles: ['REGISTRAR'] as const,
  },
  {
    email: 'methodist@demo.example.kz',
    lastNameKk: 'Жақсылықов', firstNameKk: 'Марат',
    lastNameRu: 'Жаксылыков', firstNameRu: 'Марат',
    lastNameEn: 'Zhaksylykov', firstNameEn: 'Marat',
    departmentCode: 'CS',
    position: 'методист кафедры',
    roles: ['METHODIST'] as const,
  },
];

/** Фамилии и имена для генерации демо-контингента */
export const STUDENT_NAMES: [string, string, string, string, string, string][] = [
  ['Ахметов', 'Айдос', 'Ерланұлы', 'Ахметов', 'Айдос', 'Ерланович'],
  ['Оспанова', 'Дана', 'Қайратқызы', 'Оспанова', 'Дана', 'Кайратовна'],
  ['Сейтқали', 'Айгүл', 'Мұратқызы', 'Сейткали', 'Айгуль', 'Муратовна'],
  ['Жұмабек', 'Нұрлан', 'Асқарұлы', 'Жумабек', 'Нурлан', 'Аскарович'],
  ['Қасымова', 'Мадина', 'Талғатқызы', 'Касымова', 'Мадина', 'Талгатовна'],
  ['Бекжан', 'Тимур', 'Сериктегі', 'Бекжан', 'Тимур', 'Серикович'],
  ['Ибраева', 'Асель', 'Нұрланқызы', 'Ибраева', 'Асель', 'Нурлановна'],
  ['Мұқанов', 'Дархан', 'Бақытұлы', 'Муканов', 'Дархан', 'Бакытович'],
  ['Сүлейменова', 'Жанель', 'Ерікқызы', 'Сулейменова', 'Жанель', 'Ериковна'],
  ['Тоқтаров', 'Санжар', 'Алмасұлы', 'Токтаров', 'Санжар', 'Алмасович'],
  ['Нұрсейт', 'Камила', 'Дәуренқызы', 'Нурсеит', 'Камила', 'Дауреновна'],
  ['Байтұрсын', 'Алихан', 'Мақсатұлы', 'Байтурсын', 'Алихан', 'Максатович'],
  ['Ерғалиева', 'Айым', 'Жанатқызы', 'Ергалиева', 'Айым', 'Жанатовна'],
  ['Смағұлов', 'Ілияс', 'Русланұлы', 'Смагулов', 'Ильяс', 'Русланович'],
  ['Досжан', 'Аружан', 'Мұратқызы', 'Досжан', 'Аружан', 'Муратовна'],
  ['Қуанышев', 'Бекзат', 'Ғалымұлы', 'Куанышев', 'Бекзат', 'Галимович'],
  ['Абдулла', 'Тоғжан', 'Серікқызы', 'Абдулла', 'Тогжан', 'Сериковна'],
  ['Рахимов', 'Азамат', 'Қанатұлы', 'Рахимов', 'Азамат', 'Канатович'],
  ['Мейрамова', 'Диана', 'Ерболқызы', 'Мейрамова', 'Диана', 'Ерболовна'],
  ['Сағадиев', 'Мирас', 'Асылұлы', 'Сагадиев', 'Мирас', 'Асылович'],
  ['Төлеген', 'Ақбота', 'Дәулетқызы', 'Тулеген', 'Акбота', 'Даулетовна'],
  ['Исин', 'Райымбек', 'Нұрбекұлы', 'Исин', 'Раимбек', 'Нурбекович'],
  ['Жанайдар', 'Сабина', 'Ілиясқызы', 'Жанайдар', 'Сабина', 'Ильясовна'],
  ['Қалиев', 'Ернар', 'Тимурұлы', 'Калиев', 'Ернар', 'Тимурович'],
  ['Амангелді', 'Аяулым', 'Бауыржанқызы', 'Амангельды', 'Аяулым', 'Бауыржановна'],
  ['Серғазы', 'Данияр', 'Айдарұлы', 'Сергазы', 'Данияр', 'Айдарович'],
  ['Нұрмағамбет', 'Динара', 'Сәкенқызы', 'Нурмагамбет', 'Динара', 'Сакеновна'],
  ['Оралбай', 'Жандос', 'Мұхтарұлы', 'Оралбай', 'Жандос', 'Мухтарович'],
  ['Бақыт', 'Мөлдір', 'Қайратқызы', 'Бакыт', 'Молдир', 'Кайратовна'],
  ['Шәріпов', 'Олжас', 'Ерғалиұлы', 'Шарипов', 'Олжас', 'Ергалиевич'],
];

/** Модули и элементы содержания демонстрационного курса «Введение в ИС» (3 кр. = 90 ч) */
export const COURSE_INF1201_MODULES = [
  {
    title: 'Информационная система как объект изучения',
    weekNumber: 1,
    items: [
      { type: 'TEXT', title: 'Понятие и назначение информационной системы', hours: 2, workType: 'LECTURE' },
      { type: 'VIDEO', title: 'Обзор: ИС в деятельности организации', hours: 1, workType: 'LECTURE',
        url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ' },
      { type: 'TEXT', title: 'Классификация информационных систем', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'Практикум: разбор ИС вуза', hours: 4, workType: 'PRACTICE' },
      { type: 'TEXT', title: 'СРО: подготовка обзора отраслевых ИС', hours: 8, workType: 'SRO' },
    ],
  },
  {
    title: 'Жизненный цикл информационной системы',
    weekNumber: 2,
    items: [
      { type: 'TEXT', title: 'Модели жизненного цикла', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'Стадии и этапы работ', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'Практикум: определение стадий для учебной ИС', hours: 4, workType: 'PRACTICE' },
      { type: 'TEXT', title: 'СРОП: консультация по выбору темы проекта', hours: 3, workType: 'SROP' },
      { type: 'TEXT', title: 'СРО: описание жизненного цикла выбранной ИС', hours: 8, workType: 'SRO' },
    ],
  },
  {
    title: 'Требования к информационной системе',
    weekNumber: 3,
    items: [
      { type: 'TEXT', title: 'Функциональные и нефункциональные требования', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'Техническое задание: структура и содержание', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'Практикум: формулирование требований', hours: 4, workType: 'PRACTICE' },
      { type: 'ASSIGNMENT', title: 'Задание: фрагмент технического задания', hours: 6, workType: 'SRO' },
      { type: 'QUIZ', title: 'Рубежный контроль 1', hours: 2, workType: 'PRACTICE' },
    ],
  },
  {
    title: 'Архитектура и качество информационных систем',
    weekNumber: 4,
    items: [
      { type: 'TEXT', title: 'Архитектурные решения: монолит и микросервисы', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'Критерии качества ИС', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'Лабораторная работа: оценка качества ИС', hours: 4, workType: 'LAB' },
      { type: 'TEXT', title: 'СРОП: защита промежуточных результатов', hours: 3, workType: 'SROP' },
      { type: 'TEXT', title: 'СРО: сравнительный анализ архитектур', hours: 8, workType: 'SRO' },
      { type: 'QUIZ', title: 'Рубежный контроль 2', hours: 2, workType: 'PRACTICE' },
    ],
  },
  {
    title: 'Итоговая аттестация',
    weekNumber: 5,
    items: [
      { type: 'TEXT', title: 'Обзорная лекция к экзамену', hours: 2, workType: 'LECTURE' },
      { type: 'TEXT', title: 'СРО: подготовка к экзамену', hours: 15, workType: 'SRO' },
    ],
  },
] as const;

/** Демонстрационные вопросы банка курса «Введение в ИС» */
export const DEMO_QUESTIONS = [
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Кредитная технология',
    difficulty: 'EASY' as const,
    text: 'Скольким академическим часам равен один академический кредит согласно ГОСО?',
    options: ['15 часов', '30 часов', '45 часов', '60 часов'],
    correct: [2],
    explanation:
      'Приказ МНВО РК от 20.07.2022 № 2, п. 29 (бакалавриат): один академический кредит равен 30 академическим часам.',
  },
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Оценивание',
    difficulty: 'EASY' as const,
    text: 'Какой минимальный рейтинг допуска требуется для допуска к экзамену?',
    options: ['30 баллов', '40 баллов', '50 баллов', '60 баллов'],
    correct: [3],
  },
  {
    type: 'MULTI_CHOICE' as const,
    topic: 'Оценивание',
    difficulty: 'MEDIUM' as const,
    text: 'Какие буквенные оценки соответствуют неудовлетворительному результату?',
    options: ['D', 'FX', 'F', 'C−', 'D+'],
    correct: [2, 3],
    explanation: 'По Приложению 1 к Типовым правилам неудовлетворительными являются FX и F.',
  },
  {
    type: 'TRUE_FALSE' as const,
    topic: 'Оценивание',
    difficulty: 'EASY' as const,
    text: 'Оценка FX даёт право на повторную сдачу экзамена без повторного изучения дисциплины.',
    options: ['Верно', 'Неверно'],
    correct: [1],
  },
  {
    type: 'TRUE_FALSE' as const,
    topic: 'Оценивание',
    difficulty: 'MEDIUM' as const,
    text: 'Оценка F позволяет пересдать экзамен без повторного изучения дисциплины.',
    options: ['Верно', 'Неверно'],
    correct: [2],
  },
  {
    type: 'SHORT_ANSWER' as const,
    topic: 'Кредитная технология',
    difficulty: 'MEDIUM' as const,
    text: 'Сколько академических часов составляет дисциплина объёмом 5 кредитов?',
    answers: ['150', '150 часов', '150 ч'],
  },
  {
    type: 'MATCHING' as const,
    topic: 'Оценивание',
    difficulty: 'MEDIUM' as const,
    text: 'Установите соответствие буквенной оценки и её цифрового эквивалента.',
    pairs: [
      ['A', '4,00'],
      ['B', '3,00'],
      ['C', '2,00'],
      ['D', '1,00'],
    ],
  },
  {
    type: 'ORDERING' as const,
    topic: 'Учебный процесс',
    difficulty: 'MEDIUM' as const,
    text: 'Расположите этапы контроля в хронологическом порядке.',
    sequence: ['Текущий контроль', 'Рубежный контроль 1', 'Рубежный контроль 2', 'Экзамен'],
  },
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Информационные системы',
    difficulty: 'MEDIUM' as const,
    text: 'Что относится к нефункциональным требованиям к информационной системе?',
    options: [
      'Формирование ведомости успеваемости',
      'Время отклика страницы не более 1,5 секунды',
      'Регистрация студента на дисциплину',
      'Выставление итоговой оценки',
    ],
    correct: [2],
  },
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Информационные системы',
    difficulty: 'HARD' as const,
    text: 'Какая модель жизненного цикла предполагает последовательное выполнение стадий без возврата?',
    options: ['Итеративная', 'Спиральная', 'Каскадная', 'Инкрементная'],
    correct: [3],
  },
  {
    type: 'MULTI_CHOICE' as const,
    topic: 'Информационные системы',
    difficulty: 'HARD' as const,
    text: 'Какие сведения обязательно передаются в информационную систему уполномоченного органа?',
    options: [
      'Текущий контроль успеваемости',
      'Промежуточная аттестация',
      'Посещаемость обучающихся',
      'Личная переписка обучающихся',
      'Итоговая аттестация',
    ],
    correct: [1, 2, 3, 5],
    explanation: 'п. 40 Типовых правил деятельности ОВПО.',
  },
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Персональные данные',
    difficulty: 'MEDIUM' as const,
    text: 'Где должны храниться персональные данные граждан Республики Казахстан?',
    options: [
      'В любой юрисдикции по выбору вуза',
      'В базах данных на территории Республики Казахстан',
      'Только в облачных сервисах ЕС',
      'Требование не установлено',
    ],
    correct: [2],
  },
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Информационные системы',
    difficulty: 'EASY' as const,
    text: 'Что из перечисленного НЕ входит в границы платформы онлайн-обучения?',
    options: [
      'Электронный журнал и ведомости',
      'Конструктор учебных курсов',
      'Бухгалтерия и оплата обучения',
      'Учёт академических кредитов',
    ],
    correct: [3],
  },
  {
    type: 'MULTI_CHOICE' as const,
    topic: 'Учебный процесс',
    difficulty: 'MEDIUM' as const,
    text: 'Какие виды учебной работы предусмотрены кредитной технологией обучения?',
    options: ['Лекция', 'Практическое занятие', 'СРОП', 'СРО', 'Стажировка в компании'],
    correct: [1, 2, 3, 4],
  },
  {
    type: 'SHORT_ANSWER' as const,
    topic: 'Оценивание',
    difficulty: 'HARD' as const,
    text: 'Рассчитайте итоговый балл: РК1 = 80, РК2 = 70, экзамен = 90. Формула по умолчанию.',
    answers: ['81', '81.0', '81,0'],
    explanation: 'Допуск = (80 + 70) / 2 = 75. Итог = 75 × 0,6 + 90 × 0,4 = 45 + 36 = 81.',
  },
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Учебный процесс',
    difficulty: 'MEDIUM' as const,
    text: 'Какой цикл дисциплин обозначается аббревиатурой ПД?',
    options: [
      'Общеобразовательные дисциплины',
      'Базовые дисциплины',
      'Профилирующие дисциплины',
      'Подготовительные дисциплины',
    ],
    correct: [3],
  },
  {
    type: 'SINGLE_CHOICE' as const,
    topic: 'Учебный процесс',
    difficulty: 'EASY' as const,
    text: 'Что означает компонент КВ в структуре образовательной программы?',
    options: [
      'Компонент по выбору',
      'Квалификационный вступительный',
      'Контрольный вопрос',
      'Курсовая работа',
    ],
    correct: [1],
  },
  {
    type: 'MULTI_CHOICE' as const,
    topic: 'Информационные системы',
    difficulty: 'HARD' as const,
    text: 'Какие критерии относятся к качеству информационной системы?',
    options: ['Надёжность', 'Производительность', 'Сопровождаемость', 'Стоимость лицензии офисного пакета'],
    correct: [1, 2, 3],
  },
  {
    type: 'ORDERING' as const,
    topic: 'Информационные системы',
    difficulty: 'HARD' as const,
    text: 'Расположите стадии жизненного цикла ИС в правильном порядке.',
    sequence: ['Формирование требований', 'Проектирование', 'Реализация', 'Внедрение', 'Сопровождение'],
  },
  {
    type: 'MATCHING' as const,
    topic: 'Учебный процесс',
    difficulty: 'MEDIUM' as const,
    text: 'Установите соответствие вида учебной работы и его расшифровки.',
    pairs: [
      ['СРО', 'Самостоятельная работа обучающегося'],
      ['СРОП', 'Самостоятельная работа под руководством преподавателя'],
      ['ООД', 'Общеобразовательные дисциплины'],
      ['БД', 'Базовые дисциплины'],
    ],
  },
];
